name: Add Environment Variables
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Create env file
        run: |
          echo "// Google API credentials" > env.js
          echo "GOOGLE_API_KEY = '${{ secrets.GOOGLE_API_KEY }}';" >> env.js
          echo "GOOGLE_CLIENT_ID = '${{ secrets.GOOGLE_CLIENT_ID }}';" >> env.js
      
      - name: Create .nojekyll file
        run: touch .nojekyll
      
      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          # Force add files even if they're in .gitignore
          git add -f env.js .nojekyll
          git commit -m "Add environment variables" || echo "No changes to commit"
          git push origin HEAD:main