name: Add Environment Variables
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0  # This gets the full history to resolve conflicts
      
      - name: Create env file
        run: |
          echo "// Google API credentials" > .env.js
          echo "GOOGLE_API_KEY = '${{ secrets.GOOGLE_API_KEY }}';" >> .env.js
          echo "GOOGLE_CLIENT_ID = '${{ secrets.GOOGLE_CLIENT_ID }}';" >> .env.js
      
      - name: Debug Info
        run: |
          echo "Current directory contents:"
          ls -la
          echo "Git status:"
          git status
          echo "Git branch:"
          git branch
      
      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git config pull.rebase false  # Choose merge strategy
      
      - name: Commit changes (with verbose output)
        run: |
          git add .env.js
          git status
          git commit -m "Add environment variables" || echo "No changes to commit"
          echo "Git status after commit:"
          git status
          echo "Attempting to pull:"
          git pull --no-rebase || echo "Pull failed, but continuing"
          echo "Git status after pull:"
          git status
          echo "Attempting to push:"
          git push 2>&1 || echo "Standard push failed, will try force push"
          echo "Attempting force push:"
          git push --force 2>&1
          echo "Final git status:"
          git status