name: Add Environment Variables
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0  # This gets the full history to resolve conflicts
      
      - name: Create env file
        run: |
          echo "// Google API credentials" > .env.js
          echo "GOOGLE_API_KEY = '${{ secrets.GOOGLE_API_KEY }}';" >> .env.js
          echo "GOOGLE_CLIENT_ID = '${{ secrets.GOOGLE_CLIENT_ID }}';" >> .env.js
      
      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git config pull.rebase false  # Choose merge strategy
      
      - name: Commit changes
        run: |
          git add .env.js
          git commit -m "Add environment variables" || echo "No changes to commit"
          git pull --no-rebase || echo "No need to pull"
          git push || echo "Push failed, trying force push"
          git push --force